# Generated by Django 5.2.7 on 2025-10-29 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ttype",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=7,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
